server:
  port: 9090

spring:
  application:
    name: API-GATEWAY
  config:
    import: configserver:http://localhost:9296
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: OrderService
          uri: lb://OrderService
          predicates:
            - Path=/order/**
          filters:
            - name: CircuitBreaker
              args:
                name: OrderService
                fallbackuri: forward:/orderServiceFallback

        - id: PaymentService
          uri: lb://PaymentService
          predicates:
            - Path=/payment/**
          filters:
            - name: CircuitBreaker
              args:
                name: PaymentService
                fallbackuri: forward:/paymentServiceFallback
        - id: ProductService
          uri: lb://ProductService
          predicates:
            - Path=/product/**
          filters:
            - name: CircuitBreaker
              args:
                name: ProductService
                fallbackuri: forward:/productServiceFallback

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
    reactor.netty.http.client: DEBUG
